# Generated by Django 5.0.7 on 2024-07-18 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='picture',
            field=models.CharField(default='example.com'),
            preserve_default=False,
        ),
    ]
